wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.16.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1729621342.646105
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.10.15
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
    session_history: code/_session_history.ipynb
